@HostAddress = http://localhost:5083
@RequestPath = api/categories

GET {{HostAddress}}/{{RequestPath}}
Accept: application/json

###

GET {{HostAddress}}/{{RequestPath}}/1
Accept: application/json

###

POST {{HostAddress}}/{{RequestPath}}
Content-Type: application/json
Accept: application/json

{
    "Name": "Category 1"
}

###

PUT {{HostAddress}}/{{RequestPath}}/1
Content-Type: application/json
Accept: application/json

{
    "Name": "Category 1 Updated"
}

###

DELETE {{HostAddress}}/{{RequestPath}}/1
Accept: applicationjson