@HostAddress = http://localhost:5083/api

GET {{HostAddress}}/products
Accept: application/json

###

GET {{HostAddress}}/products/2
Accept: application/json

###

POST {{HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
    "Name": "Product 1",
    "Description": "Product 1 Description",
    "Price": 1000.00,
    "StockQuantity": 10
}

###

PUT {{HostAddress}}/products/2
Content-Type: application/json
Accept: application/json

{
    "Name": "Product 1",
    "Description": "Product 1 Description",
    "Price": 1200.00,
    "StockQuantity": 7
}

###

DELETE {{HostAddress}}/products/1
Accept: application/json