@HostAddress = http://localhost:5083/api

GET {{HostAddress}}/sales
Accept: application/json

###

GET {{HostAddress}}/sales/5
Accept: application/json

###

POST {{HostAddress}}/sales
Content-Type: application/json
Accept: application/json

{
    "ProductId": 3,
    "QuantitySold": 1,
    "Price": 1000.00,
    "SaleDate": "2025-02-18"
}

###

PUT {{HostAddress}}/sales/3
Content-Type: application/json
Accept: application/json

{
    "ProductId": 3,
    "QuantitySold": 2,
    "Price": 1000.00,
    "SaleDate": "2025-02-18"
}

###

DELETE {{HostAddress}}/sales/3
Accept: application/json