@HostAddress = http://localhost:5083
@RequestPath = api/sales

GET {{HostAddress}}/{{RequestPath}}
Accept: application/json

###

GET {{HostAddress}}/{{RequestPath}}/5
Accept: application/json

###

POST {{HostAddress}}/{{RequestPath}}
Content-Type: application/json
Accept: application/json

{
    "ProductId": 3,
    "QuantitySold": 1,
    "Price": 1000.00,
    "SaleDate": "2025-02-18"
}

###

PUT {{HostAddress}}/{{RequestPath}}/3
Content-Type: application/json
Accept: application/json

{
    "ProductId": 3,
    "QuantitySold": 2,
    "Price": 1000.00,
    "SaleDate": "2025-02-18"
}

###

DELETE {{HostAddress}}/{{RequestPath}}/3
Accept: application/json