@HostAddress = http://localhost:5083
@RequestPath = api/storages

GET {{HostAddress}}/{{RequestPath}}
Accept: application/json

###

GET {{HostAddress}}/{{RequestPath}}/1
Accept: application/json

###

POST {{HostAddress}}/{{RequestPath}}
Content-Type: application/json
Accept: application/json

{
    "Description": "Storage 1 Description",
    "Location": "Storage 1 Location"
}

###

PUT {{HostAddress}}/{{RequestPath}}/1
Content-Type: application/json
Accept: application/json

{
    "Description": "Storage 1 Description Updated",
    "Location": "Storage 1 Location Updated"
}

###

DELETE {{HostAddress}}/{{RequestPath}}/1
Accept: application/json